lang_name: "English"
title: "Youngsu Lee's Dev Blog"
tagline: "Learning Kata"
description: "A blog for conscious growth through recording and exploration."
date_format: "%b %d, %Y"
no_translation: "Sorry, this page is not available in English."